spring:
  profiles:
    active: test

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
#
#  main:
#    allow-bean-definition-overriding: true

server:
  error:
    include-exception: true
    include-stacktrace: always